name: First pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  tests:
    run-on: ubuntu-latest
  
  services:
    mysql:
      image: mysql:8.0.21
      env:
        MYSQL_DATABASE: posts-test
        MYSQL_ROOT_PASSWORD: root
      ports:
        - 3306:3306
      options: --health-cmd="mysqladmin ping"

  seteps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.2'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: cp .env.ci .env
    - name: Install Dependencies
      run: |
        composer install -q --no-ansi --no-interaction --noscripts --no-progress
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 sotrage bootstrap/cache
    - name: phpstan
      run: ./vendor/bin/phpstan analyse --memory-limit=1G
    - name: phpinsights
      run: |
        php artisan insights --no-interaction --min-quality=90 --min-complexity=90 --min-architecture=90 --min-style=90 \
        --ansi --format=github-action
    - name: Run tests
      run: php artisan test
    - name: Generate key
      run: |
        cd api
        php artisan key:generate
        